version: '3.8'

services:
  # MySQL Database
  database:
    image: mysql:5.7
    container_name: worldle_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-worldle}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-symfony}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-symfony}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - worldle

  # PHP-FPM Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worldle_php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - vendor-data:/var/www/vendor
      - var-data:/var/www/var
    networks:
      - worldle
    depends_on:
      - database

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: worldle_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - worldle
    depends_on:
      - php

networks:
  worldle:
    driver: bridge

volumes:
  db-data:
    driver: local
  vendor-data:
    driver: local
  var-data:
    driver: local
